id: 63b7aa14c7c54ca68a8ca8b66b506571
initial_creation_type: ocr
source_metadata:
  volumes:
    1ae1f09cc0e243ff9fe5fbf019e6879a:
      base_file: v025.txt
      image_group_id: I1PD95870
      title: ''
      total_pages: 1853
      volume_number: 25
